# -*- coding: utf-8 -*-
"""prediksi_waktu_terbaik_untuk_astrophotograpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSfUUT5OUYixLJcPzoKGPm76V-FC_SA0

### **import library**
"""

import pandas as pd
import ephem
import datetime
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib

"""### baca dataset dan ambil data yang diperlukan"""

raw_df = pd.read_csv("pemalang_history_weather.csv")

raw_df['datetime'] = pd.to_datetime(raw_df['datetime'])

df_malam = raw_df[(raw_df['datetime'].dt.hour >= 19) | (raw_df['datetime'].dt.hour <= 4)].copy()

select_column = ['datetime', 'cloudcover', 'humidity', 'precip', 'visibility', 'windspeed']
df = df_malam[select_column].copy()

print(df.head())

"""### **ambil data fase bulan, dan tambabahkan kedataset**"""

def dapatkan_fase_bulan(row_waktu):
    waktu_bersih = str(row_waktu).replace('T', ' ')
    bulan = ephem.Moon()
    bulan.compute(waktu_bersih)
    return round(bulan.phase, 1)

df['moonphase'] = df['datetime'].apply(dapatkan_fase_bulan)
print(df.head())

"""### **pelabelan data**"""

def pelabelan(row):
    awan = row['cloudcover']
    lembab = row['humidity']
    hujan = row['precip']
    bulan = row['moonphase']
    pandang = row['visibility']
    angin = row['windspeed']

    if hujan > 0 or awan > 70 or pandang < 10 or angin > 25:
        return 0
    elif awan < 20 and bulan < 20 and lembab < 90 and pandang > 20 and angin < 15:
        return 2
    elif awan < 45 and bulan < 50 and pandang >= 15 and angin <= 22:
        return 1
    else:
        return 0

df['Target_Visibilitas'] = df.apply(pelabelan, axis=1)
print(df['Target_Visibilitas'].value_counts())
print(df.head())

"""### **pemisahan data test**"""

fitur = ['cloudcover', 'humidity', 'precip', 'visibility', 'windspeed', 'moonphase']
X = df[fitur]

y = df['Target_Visibilitas']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print(f"jumlah data latihan (X_train): {len(X_train)} baris")
print(f"jumlah data ujian (X_test): {len(X_test)} baris")

print(X_train.head())

"""### **pelatihan model**"""

model_astro = RandomForestClassifier(n_estimators=100, random_state=42)

model_astro.fit(X_train, y_train)

y_pred = model_astro.predict(X_test)

akurasi = accuracy_score(y_test, y_pred)
print("="*30)
print(f"akurasi: {akurasi * 100:.2f}%")
print("="*30)

print("detail klasifikasi: ")
print(classification_report(y_test, y_pred, zero_division=0))

joblib.dump(model_astro, 'model_astroshot.pkl')

"""### testing **model**"""

model_siap = joblib.load('model.pkl')

fitur = ['cloudcover', 'humidity', 'precip', 'visibility', 'windspeed', 'moonphase']

df['Hasil_Prediksi'] = model_siap.predict(df[fitur])

df_rekomendasi = df[df['Hasil_Prediksi'] >= 1].copy()

hari = {
    'Monday': 'Senin', 'Tuesday': 'Selasa', 'Wednesday': 'Rabu',
    'Thursday': 'Kamis', 'Friday': 'Jumat', 'Saturday': 'Sabtu', 'Sunday': 'Minggu'
}
df_rekomendasi['Hari'] = df_rekomendasi['datetime'].dt.day_name().map(hari)
df_rekomendasi['Tanggal'] = df_rekomendasi['datetime'].dt.strftime('%d %b %Y')
df_rekomendasi['Jam'] = df_rekomendasi['datetime'].dt.strftime('%H:%M WIB')

df_rekomendasi['Status'] = df_rekomendasi['Hasil_Prediksi'].map({2: 'IDEAL', 1: 'CUKUP OKE'})

df_rekomendasi = df_rekomendasi.sort_values(by='Hasil_Prediksi', ascending=False)


print("10 jadwal terrbaik yang paling direkomendasikan melihat bentnag:\n")
kolom_tampil = ['Hari', 'Tanggal', 'Jam', 'Status', 'cloudcover', 'moonphase']
print(df_rekomendasi[kolom_tampil].to_string(index=False))